import img from "../../utilis/images/lib/08_desktop.jpg";
import img1 from "../../utilis/images/chairs/bristol-chair.png";
import img2 from "../../utilis/images/chairs/bristol-chair-color-1.png";
import img3 from "../../utilis/images/chairs/bristol-chair-color-2.png";
import img33 from "../../utilis/images/chairs/bristol-chair-color-3.png";
import img4 from "../../utilis/images/chairs/bristol-chair-color-4.png";
import img5 from "../../utilis/images/chairs/manette-pillow.png";
import imgm from "../../utilis/images/chairs/marais-chair.png";
import imgm1 from "../../utilis/images/chairs/marais-chair-color-1.png";
import imgm2 from "../../utilis/images/chairs/marais-chair-color-2.png";
import imgm3 from "../../utilis/images/chairs/marais-chair-color-3.png";
import imgm4 from "../../utilis/images/chairs/marais-chair-color-4.png";

export const head = {
  title: "Read our blog posts",
  name: "All Categories",
};

export const postes = [
  {
    id:"1",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Event Design and Production",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"2",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Creative Services Agency",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"3",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Floral Design",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"4",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Printing Services",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"5",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Floral Design",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"6",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Printing Services",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"7",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Custom Fabrication",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"8",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Wedding",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"9",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Printing Services",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"10",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Printing Services",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"11",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Custom Fabrication",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
  {
    id:"12",
    img: img,
    userName: "Lily Yeung",
    date: "Sep 30",
    category: "Floral Design",
    heading: "A Taste Explosion: Event Design Extravaganza at Boa Restaurant",
    p: " Beverly Hills, renowned for its luxury and panache, witnessed an unforgettable evening that melded culinary wonders with unmatched event Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    pp: "When it comes to creating one-of-a-kind experiences, Blueprint Studios knows how to conjure magic. This event was no exception. From jousting knights to a candlelit dinner in a wine cellar, followed by a dessert reception under the stars, this event was a transportive experience right out of the pages of a storybook.",
    heading1:"The Setting",
    p1:"Castello di Amorosa, a Tuscan-style castle and winery located in Napa Valley, was the perfect setting for this enchanting event. The castle, a 121,000-square-foot fortress set upon a sprawling 171 acres, complete with a drawbridge, moat, chapel, and even a torture chamber, served as the idyllic backdrop for a medieval-themed celebration.",
    heading2:"The Reception",
    p2: "The event kicked off with a reception like no other. Guests were greeted at the castle gates with goblets of wine before entering a medieval world of wonder. As the sun set over the Napa Valley, the courtyard was alive with the sights and sounds of a medieval tournament. Knights in shining armor jousting, sword-fighting demonstrations, and falconry displays entertained guests as they mingled and sipped on the finest wines from the Castello's collection.",
    tags: {
      tag1: "Corporate",
      tag2: "Event Design and Production",
      tag3: "Creative Services Agency",
      tag4: "Custom Fabrication",
      tag5: "Custom Fabrication",
      tag6: "Custom Fabrication",
      tag7: "Custom Fabrication",
      tag8: "Custom Fabrication",
    },
  },
];

export const productSlider = [
  {
    name: "Bristol Chair",
    img1: img1,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
  {
    name: "Manette Pillow",
    img1: img5,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
  {
    name: "Marais Chair",
    img1: imgm,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
  {
    name: "Bristol Chair",
    img1: imgm1,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
  {
    name: "Manette Pillow",
    img1: imgm2,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
  {
    name: "Manette Pillow",
    img1: imgm3,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
  {
    name: "Marais Chair",
    img1: imgm4,
    btntext: "View more",
    list: {
      img2: img2,
      img3: img3,
      img4: img33,
      img5: img4,
    },
  },
];

export const postDetail = {
  id:"1",
  
}